import { Montserrat } from "next/font/google";
import "./globals.css";

import MainNav from "./components/layoutComponents/MainNav";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainNav />
        <section className="px-4 md:px-8 lg:px-12 pb-12 bg-gray-100 min-h-screen">
          {children}
        </section>
      </body>
    </html>
  );
}
